-- 1. Створення таблиці Lots (Лоти)
CREATE TABLE public.lots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_key TEXT NOT NULL,
  description_key TEXT NOT NULL,
  category_key TEXT NOT NULL,
  start_price NUMERIC NOT NULL,
  current_price NUMERIC NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  bids_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Створення таблиці Bids (Ставки)
CREATE TABLE public.bids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lot_id BIGINT REFERENCES public.lots(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  anon_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Встановлюємо RLS (Row Level Security) політики
ALTER TABLE public.lots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bids ENABLE ROW LEVEL SECURITY;

-- Усі можуть бачити лоти
CREATE POLICY "Lots are viewable by everyone." 
ON public.lots FOR SELECT USING (true);

-- Усі можуть бачити ставки
CREATE POLICY "Bids are viewable by everyone." 
ON public.bids FOR SELECT USING (true);

-- Тільки авторизовані можуть робити ставки
CREATE POLICY "Users can insert bids" 
ON public.bids FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Тільки адмін може створювати лоти (політика за умови що role зберігається в app_metadata)
CREATE POLICY "Admins can manage lots" 
ON public.lots FOR ALL USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- 3. Функція для безпечного створення першого користувача як admin
-- Цей код створює тригер, який автоматично додає role: 'user' до нових користувачів
-- Щоб зробити користувача адміном, потрібно вручну виконати:
-- update auth.users set raw_app_meta_data = raw_app_meta_data || '{"role": "admin"}'::jsonb where email = 'admin@example.com';
